=== endremborza/endremborza.github.io/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="blocks" type="BlockType" />
        <xs:element name="linktypes" type="LinkTypeType" />
      </xs:sequence>
    </xs:complexType>

    <xs:key name="LinkKey">
      <xs:selector xpath="linktypes/link" />
      <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="ParentRef" refer="LinkKey">
      <xs:selector xpath="blocks/block/type" />
      <xs:field xpath="." />
    </xs:keyref>


  </xs:element>

  <xs:complexType name="BlockType">
    <xs:sequence>
      <xs:element name="block" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="elem" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="title" type="xs:string" />
                  <xs:element name="description" type="xs:string" minOccurs="0" />
                </xs:sequence>
                <xs:attribute name="type" type="xs:string" use="required" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="LinkTypeType">
    <xs:sequence>
      <xs:element name="linktype" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string" />
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>


</xs:schema>

=== endremborza/endremborza.github.io/static/data/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema.xsd">
	<blocks>
		<block>
			<title>I made</title>
			<elem type="text">
				<title>Rankless, a quick and pretty interactive visualization platform, built on massive data</title>
			</elem>
			<elem type="text">
				<title>contributions to papers where the data was too large, complex or difficult to collect and process</title>
			</elem>
			<elem type="text">
				<title>ML models and integer optimization software to optimize logistics of perishable goods, and assess the performance of soccer teams and players</title>
			</elem>
			<elem type="text">
				<title>curricula for courses that I ended up teaching, about programming, data engineering and applied machine learning</title>
			</elem>
			<elem type="text">
				<title>a bunch of small, open-source stuff to make my life and/or work easier</title>
			</elem>

		</block>
		<block>
			<title>I like</title>
			<elem type="text">
				<title>Knowledge Management</title>
			</elem>
			<elem type="text">
				<title>Health and Longevity</title>
			</elem>
			<elem type="text">
				<title>Football, D&amp;D, StarCraft and Chess</title>
			</elem>
			<elem type="text">
				<title>Film and Popular Culture</title>
			</elem>
		</block>
		<block>
			<title>I use</title>
			<elem type="text">
				<title>python, Rust, svelte to build</title>
			</elem>
			<elem type="text">
				<title>neovim, linux with leftwm and a split-keyboard to show off</title>
			</elem>
			<elem type="text">
				<title>AI mostly from the command line and rather selectively, but appreciatively</title>
			</elem>
		</block>
	</blocks>
	<linktypes>
		<linktype id="emb-gh">
			<name>EMB GitHub link</name>
		</linktype>
	</linktypes>
</root>
